import { brandName } from "../root";

export const onboardingConfig = [
  {
    stepLabel: "User Name",
    title: "What's your user name?",
    description: "Tell us about your username",
    id: "userName",
    label: "User Name",
    placeholder: "username",
    inputType: "text",
    isMandatory: true,
  },
  {
    stepLabel: "Brand",
    title: "What's your brand name?",
    description: "Tell us the name of your brand",
    id: "brandName",
    label: "Brand Name",
    placeholder: brandName,
    inputType: "text",
    isMandatory: true,
  },
  {
    stepLabel: "Audience",
    title: "What's your Target Audience?",
    description: "Tell us about your audience",
    id: "targetAudience",
    label: "Target Audience",
    placeholder: "Developers, Kids, etc",
    inputType: "text",
    isMandatory: true,
  },
  {
    stepLabel: "Website",
    title: "What's your website?",
    description: "Enter your website URL to get started",
    id: "website",
    label: "Website URL",
    placeholder: "https://example.com",
    inputType: "text",
    isMandatory: false,
  },
  {
    stepLabel: "Niche",
    title: "What's your niche?",
    description: "Select the category that best describes your content",
    id: "niche",
    label: "Your Niche",
    placeholder: "Enter a niche",
    inputType: "text",
    isMandatory: true,
  },
  {
    stepLabel: "Competitors",
    title: "Who are your YouTube competitors?",
    description: "Add links to YouTube channels similar to yours",
    id: "competitors",
    label: "YouTube Competitor",
    placeholder: "https://youtube.com/channel/...",
    inputType: "multi-text",
    isMandatory: true,
  },
];
